fullnameOverride: crunchy-postgres-tools
deploymentName: crunchy-postgres

deployer:
  namespace: # d8d909-tools
  serviceAccount:
    enabled: true

provisioner:
  serviceAccount:
    enabled: true

linter:
  serviceAccount:
    enabled: true

networking:
  # Network policy to allow traffic from outside the namespace (like the internet)
  networkPolicy:
    enabled: true
  # Pod network policy to allow pods to accept traffic from other pods in this namespace
  podNetworkPolicy:
    enabled: true
  route:
    enabled: true
    host: # eg: crunchy-postgres.apps.silver.devops.gov.bc.ca
