apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ template "crunchy-postgres.fullname" . }}
  labels: {{ include "crunchy-postgres.labels" . | nindent 4 }}
spec:
  metadata:
    labels: {{ include "crunchy-postgres.labels" . | nindent 6 }}
  image: {{ .Values.crunchyImage }}
  postgresVersion: {{ .Values.postgresVersion }}
  monitoring:
    pgmonitor:
      # this stuff is for the "exporter" container in the "postgres-cluster-ha" set of pods
      exporter:
        image: {{ .Values.pgmonitor.exporter.image}}
        resources:
          requests:
            cpu: {{ .Values.pgmonitor.exporter.requests.cpu }}
            memory: {{ .Values.pgmonitor.exporter.requests.memory }}
          limits:
            cpu: {{ .Values.pgmonitor.exporter.limits.cpu }}
            memory: {{ .Values.pgmonitor.exporter.limits.memory }}
  instances:
    - name: {{ .Values.instances.name }}
      replicas: {{ .Values.instances.replicas }}
      resources:
        requests:
          cpu: {{ .Values.instances.resources.requests.cpu }}
          memory: {{ .Values.instances.resources.requests.memory }}
        limits:
          cpu: {{ .Values.instances.resources.limits.cpu }}
          memory: {{ .Values.instances.resources.limits.memory }}
      sidecars:
        replicaCertCopy:
          resources:
            requests:
              cpu: {{ .Values.instances.sidecars.replicaCertCopy.resources.requests.cpu }}
              memory: {{ .Values.instances.sidecars.replicaCertCopy.resources.requests.memory }}
            limits:
              cpu: {{ .Values.instances.sidecars.replicaCertCopy.resources.limits.cpu }}
              memory: {{ .Values.instances.sidecars.replicaCertCopy.resources.limits.memory }}
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.dataVolumeClaimSpec.storage }}
        storageClassName: netapp-block-standard
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster:
                      {{ template "crunchy-postgres.fullname" . }}
                    postgres-operator.crunchydata.com/instance-set: {{ .Values.instances.name }}-ha
  users:
    - name: {{ template "crunchy-postgres.fullname" . }}
      databases:
        - {{ template "crunchy-postgres.fullname" . }}
      options: "CREATEROLE"
    - name: postgres
      databases:
        - {{ template "crunchy-postgres.fullname" . }}
  backups:
    pgbackrest:
      image: {{ .Values.pgbackrest.image }}
      global:
        repo1-retention-full: {{ .Values.pgbackrest.retention | quote }}
      repos:
        - name: {{ .Values.pgbackrest.repos.name }}
          schedules:
            full: {{ .Values.pgbackrest.repos.schedules.full }}
            incremental: {{ .Values.pgbackrest.repos.schedules.incremental }}
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: {{ .Values.pgbackrest.repos.volume.storage }}
              storageClassName:
                {{ .Values.pgbackrest.repos.volume.storageClassName }}
      # this stuff is for the "pgbackrest" container (the only non-init container) in the "postgres-crunchy-repo-host" pod
      repoHost:
        resources:
          requests:
            cpu: {{ .Values.pgbackrest.repoHost.resources.requests.cpu }}
            memory: {{ .Values.pgbackrest.repoHost.resources.requests.memory }}
          limits:
            cpu: {{ .Values.pgbackrest.repoHost.resources.limits.cpu }}
            memory: {{ .Values.pgbackrest.repoHost.resources.limits.memory }}
      sidecars:
        # this stuff is for the "pgbackrest" container in the "postgres-crunchy-ha" set of pods
        pgbackrest:
          resources:
            requests:
              cpu: {{ .Values.pgbackrest.sidecars.resources.requests.cpu }}
              memory: {{ .Values.pgbackrest.sidecars.resources.requests.memory }}
            limits:
              cpu: {{ .Values.pgbackrest.sidecars.resources.limits.cpu }}
              memory: {{ .Values.pgbackrest.sidecars.resources.limits.memory }}
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "host all all 0.0.0.0/0 md5"
        parameters:
          shared_buffers: {{ .Values.patroni.postgresql.parameters.shared_buffers }}
          wal_buffers: {{ .Values.patroni.postgresql.parameters.wal_buffers }}
          min_wal_size: {{ .Values.patroni.postgresql.parameters.min_wal_size }}
          max_wal_size: {{ .Values.patroni.postgresql.parameters.max_wal_size }}
          max_slot_wal_keep_size:  {{ .Values.patroni.postgresql.parameters.max_slot_wal_keep_size }}
  proxy:
    pgBouncer:
      config:
        global:
          client_tls_sslmode: disable
      image: {{ .Values.proxy.pgBouncer.image }}
      replicas: {{ .Values.proxy.pgBouncer.replicas }}
      # these resources are for the "pgbouncer" container in the "hippo-ha-pgbouncer" set of pods
      # there is a sidecar in these pods which are not mentioned here, but the requests/limits are teeny weeny by default so no worries there.
      resources:
        requests:
          cpu: {{ .Values.proxy.pgBouncer.resources.requests.cpu }}
          memory: {{ .Values.proxy.pgBouncer.resources.requests.memory }}
        limits:
          cpu: {{ .Values.proxy.pgBouncer.resources.limits.cpu }}
          memory: {{ .Values.proxy.pgBouncer.resources.limits.memory }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster:
                      {{ .Values.instances.name }}
                    postgres-operator.crunchydata.com/role: pgbouncer
