{{- if and .Values.networking.networkPolicy.enabled .Values.networking.isNSX }}

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ or .Values.deploymentName .Release.Name }}-operator
  labels:
{{ include "crunchy-postgres-tools.labels" . | indent 4}}
spec:
  # This policy allows the operator to reach the Crunchy pods
  egress:
    - ports:
        - port: 8432
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-bcgov-crunchy
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-bcgov-crunchy
      ports:
        - port: 8432
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: crunchy-postgres
  policyTypes:
    - Egress
    - Ingress
{{- end }}
