{{ if and .Values.deployer.serviceAccount.enabled (eq .Release.Namespace .Values.deployer.namespace) }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-deployer
  labels:
{{ include "crunchy-postgres-tools.labels" . | indent 4 }}
  namespace: {{ .Values.deployer.namespace }}

{{ end }}
