{{ if .Values.deployer.serviceAccount.enabled }}

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-deployer
  labels:
{{ include "crunchy-postgres-tools.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-deployer
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-deployer
    namespace: {{ .Values.deployer.namespace }}


{{ end }}
