# Deploy to OpenShift namespaces
name: deploy-chart

on:
  workflow_call:
    secrets:
      OPENSHIFT_SERVER: { required: true }
      OPENSHIFT_TOKEN: { required: true }
      OPENSHIFT_NAMESPACE: { required: true }
      OPENSHIFT_ROUTE: { required: true }
      NAMESPACE_PREFIX: { required: true }

env:
  TAG: sha-${{ github.sha }}

jobs:
  deploy-to-openshift-development:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: "dev"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          openshift_route: ${{ secrets.OPENSHIFT_ROUTE }}
          openshift_namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

  deploy-to-openshift-test:
    needs: [deploy-to-openshift-development]
    runs-on: ubuntu-latest
    environment:
      name: test
      url: "test"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          openshift_route: ${{ secrets.OPENSHIFT_ROUTE }}
          openshift_namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

  deploy-to-openshift-production:
    needs: [deploy-to-openshift-test]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: "prod"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          openshift_route: ${{ secrets.OPENSHIFT_ROUTE }}
          openshift_namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
