name: deploy tools chart

on:
  workflow_call:
    secrets:
      OPENSHIFT_SERVER: { required: true }
      OPENSHIFT_TOKEN: { required: true }
      NAMESPACE_PREFIX: { required: true }

jobs:
  deploy-to-openshift-tools:
    runs-on: ubuntu-latest
    environment:
      name: tools
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Authenticate, set context and run deploy script
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
      - run: |
          chmod +x .bin/helm_deploy.sh
          .bin/helm_deploy.sh -pp ${{ secrets.NAMESPACE_PREFIX }} -ps tools -c ./charts/tools/ -n crunchy-postgres-tools -v ./charts/tools/values.yaml
        shell: bash
