name: Release Yaml

# There is definitely room to streamline this release process though for now this is being called on push tags:
# eg: git tag -a raw-yaml-v.0.2.0 -m "Release v0.2.0"
#     git push --tags

on:
  push:
    tags:
      - "*"

jobs:
  release-yaml:
    name: Eject yaml and upload to release
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v1

      - name: Eject charts
        run: |
          helm template --output-dir yaml charts/crunchy-postgres
          helm template -f charts/tools/values-provision.yaml --output-dir yaml charts/tools
          zip crunchy-postgres-yaml.zip ./yaml/**/templates/*.yaml ./yaml/**/templates/**/*.yaml -r

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: yaml/.
          config_data: |
            extends: default
            rules:
              trailing-spaces:
                level: warning
              line-length:
                level: warning

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: crunchy-postgres-yaml.zip
          asset_name: crunchy-postgres-yaml.zip
          tag: ${{ github.ref }}
          overwrite: true

  release-chart:
    needs: [release-yaml]
    uses: ./.github/workflows/release-chart.yaml
    secrets: inherit
