name: Release Chart

on: release

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true

  release-yaml:
    name: Eject yaml and upload to release
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v1

      - name: Eject charts
        run: |
          helm template --output-dir ./yaml ./charts/crunchy-postgres
          helm template --output-dir ./yaml ./charts/tools
          zip crunchy-postgres-release.zip ./yaml/**/templates/*.yaml ./yaml/**/templates/**/*.yaml -r

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: crunchy-postgres-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
