# Tests
name: test code

on:
  workflow_call:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./.bin/install-gitleaks-linux-x64.sh
      - run: ./gitleaks detect --exit-code 0 --report-format sarif --report-path "gitleaks.sarif"
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "gitleaks.sarif"

  # lint-tools-chart:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: tools
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Authenticate to OpenShift Linter namespace
  #       uses: redhat-actions/oc-login@v1
  #       with:
  #         openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
  #         openshift_token: ${{ secrets.OPENSHIFT_LINTER_TOKEN }}
  #         insecure_skip_tls_verify: true
  #     - run: |
  #         set -euo pipefail; \
  #         helm dep up ./charts/tools; \
  #         helm template -f ./charts/tools/values.yaml crunchy-postgres ./charts/tools --validate;

  # lint-crunchy-postgres-chart:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: tools
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Authenticate to OpenShift Linter namespace
  #       uses: redhat-actions/oc-login@v1
  #       with:
  #         openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
  #         openshift_token: ${{ secrets.OPENSHIFT_LINTER_TOKEN }}
  #         insecure_skip_tls_verify: true
  #     - run: |
  #         set -euo pipefail; \
  #         helm dep up ./charts/crunchy-postgres; \
  #         helm template -f ./charts/crunchy-postgres/values.yaml crunchy-postgres ./charts/crunchy-postgres --validate;

  lint-raw-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v1
      - name: Eject charts
        uses: ./.github/actions/eject-chart
      - name: Scan with kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: yaml
